# Generated by Django 3.1.4 on 2020-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Produt',
        ),
    ]
