# Generated by Django 3.1.4 on 2020-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('dataTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
